services:
  - type: web
    name: bad-posture-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/main.py
    autoDeploy: true
