services:
  - type: web
    name: bad-posture-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py  # or backend/main.py if that's the start
    autoDeploy: true
